### ISSUE TITLE
[1.12.2] Slim Player Models won't work at first unless you respawn.

### ISSUE THREAD

**Issue by Z-Tunic** [Meldexun/EntityCulling#63]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 3
[___MixinCompat-0.8___]
_MixinBootstrap-1.1.0
EntityCulling-1.12.2-5.3.1

-----

It seems that Slim Player Models won't be used at first unless you respawn from death so instead it uses the Classic Player Model. Upon respawning from death... it then uses the Slim Player Model.

![entitycullplayermodelbug](https://user-images.githubusercontent.com/36653806/166096379-6979426b-08bb-4fc6-b143-59a69a3bfc4f.png)
Left: The Player Model is using the Classic Model upon loading a world, which is why the skin texture is broken.
Right: Respawning after doing a "/kill". Upon respawning... it then uses the Slim Player Model. The skin texture works correctly now.

=====

Now... I dunno why this occurs with Entity Culling, but without it installed this bug doesn't occur. This was done with a fresh config too.

*EDIT*
This bug doesn't occur if using `EntityCulling-1.12.2-5.2.3`.

**Comment by Meldexun** [comment]
I am unable to reproduce this. Please use the issue template and provide all the requested information.

**Comment by Z-Tunic** [comment]
Mods are the same as the OP, using `EntityCulling-1.12.2-5.3.1`.

Steps:
1. Start a new world, or rejoin a world, either one.
2. Enter third-person mode, if you aren't already.
3. Player Model will be using their Classic Player Model, if you have the Slim Player Model selected for your character.
4. Get slain by a mob, or fall from a great height, use /kill.
5. Respawn and you should see your character use the Slim Player Model.

If you should leave the world & rejoin, you'll revert back to the Classic Player Model.

Log:
[latest.log](https://github.com/Meldexun/EntityCulling/files/8596628/latest.log)

Debug:
[debug.log](https://github.com/Meldexun/EntityCulling/files/8596630/debug.log)

Screenshots:
![entitycullplayermodelbugDefaultSkinTexure](https://user-images.githubusercontent.com/36653806/166100890-688b6b4d-5757-4870-b7fe-3f4310e29470.png)
Left is the player using the Classic Player Model, even though they have Slim Player Model selected.
Right is the player using the Slim Player Model after respawning from death.

I am using the default texture for the Slim Player Model for texting purposes.

**Comment by Meldexun** [comment]
I'm still unable to reproduce this and there is nothing unusual in the logs.

**Comment by Z-Tunic** [comment]
I brought out my old PC just to test with the above mods, and the same thing happens... though the forge version was... 14.23.5.2855 I think.

The above posts was done with Windows 7, Intel i7-8700k, GTX 1080ti, and 32 GB DDR4 RAM.

Old PC had... Windows 7, Intel i5-4670k, GTX 970, and 16GB DDR3(?) RAM.

For both games... I ran with the default java version that came bundled with the Minecraft Installer as well as using the default JVM arguments.

I really don't know what else to do since I was able to get this to happen on my current PC, as well as my old PC, though I did try messing with the config for my current PC. I set...

`# Disable all changes from this mod (This is not equal to removing the mod!).` to "false" 

...and the above bug in the images did not occur, other options were messed with but only that option did something.

**Comment by nerdula** [comment]
Would like to second this as I seem to be having the same issue of the player being rendered with the full size model rather than the slim arms one even with fresh configs for Entity Culling and Forge. Pics are basically the exact same as above along with the fix of needing to be killed in any way. Based on some quick tests, java versions and JVM args don't seem to fix or change anything. Best thing I could think of was maybe something with Nvidia drivers and settings but I don't really want to test that so if anyone else wants to they can.

Minecraft 1.12.2, Forge 14.23.5.2860 with a i7-9700 and GTX 1660Ti
Entity Culling 1.12.2-5.3.1 with either MixinBooter or MixinBootstrap (No difference)

[latest.log] (https://github.com/Meldexun/EntityCulling/files/8598338/latest.log)

**Comment by Meldexun** [comment]
Should be fixed in v1.12.2-5.3.2

**Comment by Z-Tunic** [comment]
Bug still occurs with... EntityCulling-1.12.2-5.3.2, same as the above screenshots, same mods besides updating EntityCulling.

Log:
[latest.log](https://github.com/Meldexun/EntityCulling/files/8600262/latest.log)

Debug:
[debug.log](https://github.com/Meldexun/EntityCulling/files/8600263/debug.log)

Tests were done by making an new world, Player Model was using the Classic Model until you respawned from death, then you'll switch to the Slim Player Model. I also left & rejoined the world which went back to the Classic Player Model.

**Comment by nerdula** [comment]
Bug also continues to occur for me with the updated 5.3.2 jar so something is still bugged. Results are the exact same as Z-Tunic said above.

[latest.log](https://github.com/Meldexun/EntityCulling/files/8600807/latest.log)

**Comment by Meldexun** [comment]
[EntityCulling-1.12.2-5.3.3-pre1.jar.zip](https://github.com/Meldexun/EntityCulling/files/8602772/EntityCulling-1.12.2-5.3.3-pre1.jar.zip)
Can you test this version?

**Comment by Z-Tunic** [comment]
Testing the prelrease, I bring good news...
![2022-05-02 07-29-41](https://user-images.githubusercontent.com/36653806/166235254-c25590aa-ffd5-44d7-a458-138bcf673844.gif)
The bug seems to no longer occur. Also tested this is a heavily modded survival world and the bug doesn't occur there either.

**Comment by Meldexun** [comment]
Should be fixed in v1.12.2-5.3.3
